/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demo;
import static demo.Career.ui;
import java.io.BufferedReader;

import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.Random;
import weka.classifiers.Classifier;
import weka.classifiers.Evaluation;
import weka.classifiers.trees.RandomForest;
import weka.core.Instances;
import java.io.FileOutputStream;
import java.io.FileWriter;
import javax.swing.JOptionPane;


public class UserInput extends javax.swing.JFrame {
    public static String fe,se,te,be,output,classDetails;
    public static int v,tech,nontech,techplus,course,hack;
    public static String[] temp=new String[100];
    public static int cnt=0;
    
    /**
     * Creates new form UserInput
     */
    public UserInput() {
        this.setExtendedState(MAXIMIZED_BOTH);
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cb_hack = new javax.swing.JComboBox<>();
        cb_eventsNonTech = new javax.swing.JComboBox<>();
        cb_vol = new javax.swing.JComboBox<>();
        cb_eventsTech = new javax.swing.JComboBox<>();
        cb_eventsTechplus = new javax.swing.JComboBox<>();
        cb_course = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(13, 248, 248));
        jLabel1.setText("FE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 270, 30, 30);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(13, 248, 248));
        jLabel2.setText("TE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 360, 25, 21);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(13, 248, 248));
        jLabel3.setText("SE ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 310, 30, 30);

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(13, 248, 248));
        jLabel4.setText("<html>Coding practice on <br> hackerrank, codechef etc </html>");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(810, 170, 234, 40);

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(13, 248, 248));
        jLabel5.setText("BE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 400, 27, 21);

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(13, 248, 248));
        jLabel6.setText("Events volunteered ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(810, 230, 183, 21);

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(13, 248, 248));
        jLabel7.setText("Technical courses ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(810, 430, 230, 21);

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(13, 248, 248));
        jLabel8.setText("Technical events ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(810, 280, 160, 21);

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(13, 248, 248));
        jLabel9.setText("Technical++ events");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(810, 320, 181, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(351, 204, 0, 0);

        jButton1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jButton1.setText("Click to predict");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(550, 510, 210, 29);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1326, 604, 0, 0);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1180, 635, 120, 30);

        jLabel12.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(13, 248, 248));
        jLabel12.setText("Academic Details");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(240, 130, 180, 30);

        jTextField1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jTextField1.setNextFocusableComponent(jTextField2);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(340, 270, 65, 30);

        jTextField2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jTextField2.setNextFocusableComponent(jTextField3);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(340, 310, 65, 30);

        jTextField3.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jTextField3.setNextFocusableComponent(jTextField4);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(340, 350, 65, 30);

        jTextField4.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jTextField4.setNextFocusableComponent(cb_hack);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 390, 65, 30);

        jLabel13.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(13, 248, 248));
        jLabel13.setText("Extra Curricular Activities");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(910, 110, 370, 21);

        jLabel14.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(13, 248, 248));
        jLabel14.setText("Non-technical events");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(810, 380, 196, 21);

        cb_hack.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_hack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Very Frequently", "Frequently", "Sometimes", "Never" }));
        cb_hack.setSelectedIndex(-1);
        cb_hack.setNextFocusableComponent(cb_vol);
        cb_hack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hackActionPerformed(evt);
            }
        });
        getContentPane().add(cb_hack);
        cb_hack.setBounds(1080, 180, 130, 20);

        cb_eventsNonTech.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_eventsNonTech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cb_eventsNonTech.setSelectedIndex(-1);
        cb_eventsNonTech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_eventsNonTechActionPerformed(evt);
            }
        });
        getContentPane().add(cb_eventsNonTech);
        cb_eventsNonTech.setBounds(1080, 330, 130, 20);

        cb_vol.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_vol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frequently", "Sometimes", "Never" }));
        cb_vol.setSelectedIndex(-1);
        cb_vol.setNextFocusableComponent(cb_eventsTech);
        getContentPane().add(cb_vol);
        cb_vol.setBounds(1080, 230, 130, 20);

        cb_eventsTech.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_eventsTech.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cb_eventsTech.setSelectedIndex(-1);
        cb_eventsTech.setNextFocusableComponent(cb_eventsTechplus);
        getContentPane().add(cb_eventsTech);
        cb_eventsTech.setBounds(1080, 280, 130, 20);

        cb_eventsTechplus.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_eventsTechplus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cb_eventsTechplus.setSelectedIndex(-1);
        getContentPane().add(cb_eventsTechplus);
        cb_eventsTechplus.setBounds(1080, 380, 130, 20);

        cb_course.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        cb_course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        cb_course.setSelectedIndex(-1);
        cb_course.setNextFocusableComponent(jButton1);
        getContentPane().add(cb_course);
        cb_course.setBounds(1080, 430, 130, 20);

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Project_code-20170527T063326Z-001\\Project_code\\Images\\help12.png")); // NOI18N
        jLabel15.setToolTipText("<html>\n<title> <h4><b> How to rate a  student in events particippation</b> </h4> </title>\nA: Frequently participates and clears their way to finals <br>\nB: Frequently participates <br>\nC: Rarely Participates \n</html>");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(1220, 280, 20, 20);

        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/demo/help12.png"))); // NOI18N
        jLabel16.setToolTipText("<html>\n<title> <h4><b> How to rate a  student in technologies/courses</b> </h4> </title>\nA: Has considerable knowledge of latest technologies (Hadoop, Cloud etc) <br>\nB: Has knowledge of basic technologies (C,CPP,Java etc) <br>\nC: Average inthis domain\n</html>");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(1220, 430, 20, 20);

        jLabel17.setText("Logo");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1160, 30, 60, 50);

        jLabel18.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(13, 248, 248));
        jLabel18.setText("Explicit Prediction");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(530, 10, 510, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\Project_code-20170527T063326Z-001\\Project_code\\Images\\bb1.jpg")); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(-50, -50, 1640, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

     fe = jTextField1.getText();
     se = jTextField2.getText();
     te = jTextField3.getText();
     be = jTextField4.getText();
     
     
   
     v= cb_vol.getSelectedIndex();
         if(v==0) v=100; if(v==1) v=60; if(v==2) v=20;
        
     tech = cb_eventsTech.getSelectedIndex();
         if(tech==0) tech=100; if(tech==1) tech=60; if(tech==2) tech=20;

     nontech = cb_eventsNonTech.getSelectedIndex();
         if(nontech==0) nontech=100; if(nontech==1) nontech=60; if(nontech==2) nontech=20;
       
     techplus = cb_eventsTechplus.getSelectedIndex();
         if(techplus==0) techplus=100; if(techplus==1) techplus=60; if(techplus==2) techplus=20;
       
     course = cb_course.getSelectedIndex();
         if(course==0) course=100; if(course==1) course=60; if(course==2) course=20;

     hack = cb_hack.getSelectedIndex();
         if(hack==0) hack=100; if(hack==1) hack=75; if(hack==2) hack=50; if(hack==3) hack=25;
         
         
             if(jTextField1.getText().equals("")||
            jTextField2.getText().equals("")||
            jTextField3.getText().equals("")||
            jTextField4.getText().equals("")||UserInput.v==-1||
            UserInput.tech==-1 ||
            UserInput.techplus==-1||
            UserInput.nontech==-1||
            UserInput.hack==-1||
            UserInput.course==-1) {JOptionPane.showMessageDialog(null, "Please fill all the fields!");
             
             return;
             
             };
            
            
        

        try{

            FileWriter fw = new FileWriter("C:\\Users\\Admin\\Desktop\\Project_code-20170527T063326Z-001\\Project_code\\source_file\\test.arff",true); //the true will append the new data
            fw.write(fe+","+se+","+te+","+be+","+v+","+tech+","+techplus+","+nontech+","+course+","+hack+",?\n");//appends the string to the file
            fw.close();
                                System.out.println("Fie..............");
                                
        Classifier classifier = null;

        System.out.println("read training arff");

        Instances train = new Instances(new BufferedReader(new FileReader("C:\\Users\\Admin\\Desktop\\Project_code-20170527T063326Z-001\\Project_code\\source_file\\Training.arff")));
        train.setClassIndex(10);
        System.out.println("read testing arff");
        Instances unlabeled = new Instances(new BufferedReader(new FileReader("C:\\Users\\Admin\\Desktop\\Project_code-20170527T063326Z-001\\Project_code\\source_file\\test.arff")));
        unlabeled.setClassIndex(10);

        String[] algorithms = {"random"};
        for (String algorithm : algorithms) {
            if (algorithm.equals("random")) {
                classifier = new RandomForest();
            }
            System.out.println("==========================================================================");
            System.out.println("training using " + algorithm + " classifier");
            Evaluation eval = new Evaluation(train);
            //perform 10 fold cross validation
            eval.crossValidateModel(classifier, train, 10, new Random(1));
            output = eval.toSummaryString();
            
            classDetails = eval.toClassDetailsString();
            classifier.buildClassifier(train);
        }

        Instances labeled = new Instances(unlabeled);
        
        // label instances (use the trained classifier to classify new unseen instances)
        for (int i = 0; i <unlabeled.numInstances(); i++) {
            double clsLabel = classifier.classifyInstance(unlabeled.instance(i));
            labeled.instance(i).setClassValue(clsLabel);
            System.out.println(clsLabel + " -> " + unlabeled.classAttribute().value((int) clsLabel));
            temp[i]=unlabeled.classAttribute().value((int) clsLabel);
            System.out.println("\ntemp:"+temp[i]);
            cnt=i;
        }

            //save the model for future use
            ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream("myModel.dat"));
            out.writeObject(classifier);
            out.close();
            System.out.println("===== Saved model =====");

                                
                                
        }
        catch(Exception e)
        {
            
        }
      
        if(temp[cnt].equals("A"))
            JOptionPane.showMessageDialog(null,"You are likely to get placed in a dream status company.");
        else if(temp[cnt].equals("B"))
            JOptionPane.showMessageDialog(null,"You are likely to get placed in a service based company.");
        else if(temp[cnt].equals("C"))
            JOptionPane.showMessageDialog(null,"You are likely to get placed in a company which wishes to hire candidates with good marketing and communication skills.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       // Career a=new Career();
       // a.setVisible(true);
               // dispose();
               ui.setVisible(false);
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void cb_hackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hackActionPerformed

    private void cb_eventsNonTechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_eventsNonTechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_eventsNonTechActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])throws IOException, Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
            UserInput u=new UserInput();
            
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new UserInput().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_course;
    private javax.swing.JComboBox<String> cb_eventsNonTech;
    private javax.swing.JComboBox<String> cb_eventsTech;
    private javax.swing.JComboBox<String> cb_eventsTechplus;
    private javax.swing.JComboBox<String> cb_hack;
    private javax.swing.JComboBox<String> cb_vol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
